# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildFrontend
  displayName: 'Build Frontend'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Build Frontend'

- job: BuildBackend
  displayName: 'Build Backend'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      cd backend
      npm install
    displayName: 'Install Backend Dependencies'

- job: RunFrontendTests
  displayName: 'Run Frontend Tests'
  dependsOn: BuildFrontend
  steps:
  - task: NodeTool@0

  - script: |
      cd frontend
      npm run test
    displayName: 'Run Frontend Tests'

- job: RunBackendTests
  displayName: 'Run Backend Tests'
  dependsOn: BuildBackend
  steps:
  - task: NodeTool@0

  - script: |
      cd backend
      npm run test
    displayName: 'Run Backend Tests'
